# Toy Example — similarities.py 검증 (2026.04.15 기준)

`similarities.py`의 현재 구현(`compute_similarity`)을 그대로 사용하여 5×6 토이 데이터(User×Item)에 대해 모든 유사도 행렬을 계산한다.

In [1]:
import sys, warnings, importlib
import numpy as np
import pandas as pd

sys.path.insert(0, '..')          # imputation_project 루트
warnings.filterwarnings('ignore')

import utils.similarities as sim_mod
importlib.reload(sim_mod)          # 최신 파일 반영

from utils.similarities import compute_similarity, available_methods

print("사용 가능한 유사도 메서드:", available_methods())

사용 가능한 유사도 메서드: ['acos', 'ami', 'ari', 'chebyshev', 'cosine', 'cpcc', 'euclidean', 'ipwr', 'itr', 'jaccard', 'jmsd', 'kendall_tau_b', 'manhattan', 'msd', 'pcc', 'spcc', 'src']

In [2]:
# 토이 데이터 (User × Item, 5명 × 6아이템)
data = [
    [3, np.nan, 4, np.nan, np.nan, np.nan],
    [np.nan, 5, np.nan, 3, 5, 3],
    [3, 4, 4, 3, 4, 3],
    [1, 2, 1, np.nan, 2, np.nan],
    [1, np.nan, 5, np.nan, np.nan, np.nan],
]

USER_LABELS = ['U1', 'U2', 'U3', 'U4', 'U5']
ITEM_LABELS = ['I1', 'I2', 'I3', 'I4', 'I5', 'I6']

train_df = pd.DataFrame(data, index=USER_LABELS, columns=ITEM_LABELS)
print("=== 토이 데이터 (User × Item) ===")
display(train_df)

=== 토이 데이터 (User × Item) ===

     I1   I2   I3   I4   I5   I6
U1  3.0  NaN  4.0  NaN  NaN  NaN
U2  NaN  5.0  NaN  3.0  5.0  3.0
U3  3.0  4.0  4.0  3.0  4.0  3.0
U4  1.0  2.0  1.0  NaN  2.0  NaN
U5  1.0  NaN  5.0  NaN  NaN  NaN

In [3]:
# similarities.py의 compute_similarity로 모든 유사도 행렬 계산 및 출력
METHODS = available_methods()

for method in METHODS:
    try:
        S = compute_similarity(train_df, method)
        df_S = pd.DataFrame(S, index=USER_LABELS, columns=USER_LABELS).round(4)
        print(f"\n{'='*50}")
        print(f"  {method.upper()}")
        print(f"{'='*50}")
        display(df_S)
    except Exception as e:
        print(f"\n[{method}] ERROR: {e}")

==================================================
  ACOS
==================================================

        U1      U2      U3      U4      U5
U1  1.0000     NaN  0.0580 -0.2121  0.0429
U2     NaN  1.0000  0.2722  0.5685     NaN
U3  0.0580  0.2722  1.0000  0.6963  0.2462
U4 -0.2121  0.5685  0.6963  1.0000 -0.1928
U5  0.0429     NaN  0.2462 -0.1928  1.0000

==================================================
  AMI
==================================================

     U1   U2   U3   U4   U5
U1  1.0  NaN  1.0  0.0  1.0
U2  NaN  1.0  1.0  1.0  NaN
U3  1.0  1.0  1.0  0.0  1.0
U4  0.0  1.0  0.0  1.0  0.0
U5  1.0  NaN  1.0  0.0  1.0

==================================================
  ARI
==================================================

     U1   U2   U3   U4   U5
U1  1.0  NaN  1.0  0.0  1.0
U2  NaN  1.0  1.0  1.0  NaN
U3  1.0  1.0  1.0  0.0  1.0
U4  0.0  1.0  0.0  1.0  0.0
U5  1.0  NaN  1.0  0.0  1.0

==================================================
  CHEBYSHEV
==================================================

        U1    U2      U3    U4      U5
U1  1.0000   NaN  1.0000  0.25  0.3333
U2     NaN  1.00  0.5000  0.25     NaN
U3  1.0000  0.50  1.0000  0.25  0.3333
U4  0.2500  0.25  0.2500  1.00  0.2000
U5  0.3333   NaN  0.3333  0.20  1.0000

==================================================
  COSINE
==================================================

        U1      U2      U3      U4      U5
U1  1.0000     NaN  0.5774  0.4427  0.9021
U2     NaN  1.0000  0.8122  0.7670     NaN
U3  0.5774  0.8122  1.0000  0.8398  0.5208
U4  0.4427  0.7670  0.8398  1.0000  0.3721
U5  0.9021     NaN  0.5208  0.3721  1.0000

==================================================
  CPCC
==================================================

        U1   U2      U3      U4      U5
U1  1.0000  NaN  1.0000 -0.7071  0.7071
U2     NaN  1.0  1.0000 -1.0000     NaN
U3  1.0000  1.0  1.0000 -0.7303  0.7071
U4 -0.7071 -1.0 -0.7303  1.0000  0.0000
U5  0.7071  NaN  0.7071  0.0000  1.0000

==================================================
  EUCLIDEAN
==================================================

        U1      U2      U3      U4     U5
U1  1.0000     NaN  1.0000  0.2171  0.309
U2     NaN  1.0000  0.4142  0.1907    NaN
U3  1.0000  0.4142  1.0000  0.1791  0.309
U4  0.2171  0.1907  0.1791  1.0000  0.200
U5  0.3090     NaN  0.3090  0.2000  1.000

==================================================
  IPWR
==================================================

        U1      U2      U3      U4      U5
U1  1.0000     NaN  0.8955 -0.1354  0.6544
U2     NaN  1.0000  0.3449 -0.0827     NaN
U3  0.8955  0.3449  1.0000 -0.0045  0.5861
U4 -0.1354 -0.0827 -0.0045  1.0000 -0.0761
U5  0.6544     NaN  0.5861 -0.0761  1.0000

==================================================
  ITR
==================================================

        U1      U2      U3      U4      U5
U1  1.0000     NaN  0.5000  0.2189  0.5288
U2     NaN  1.0000  0.3974  0.1273     NaN
U3  0.5000  0.3974  1.0000  0.2861  0.5288
U4  0.2189  0.1273  0.2861  1.0000  0.0368
U5  0.5288     NaN  0.5288  0.0368  1.0000

==================================================
  JACCARD
==================================================

        U1      U2      U3      U4      U5
U1  1.0000  0.0000  0.3333  0.5000  1.0000
U2  0.0000  1.0000  0.6667  0.3333  0.0000
U3  0.3333  0.6667  1.0000  0.6667  0.3333
U4  0.5000  0.3333  0.6667  1.0000  0.5000
U5  1.0000  0.0000  0.3333  0.5000  1.0000

==================================================
  JMSD
==================================================

        U1      U2      U3      U4    U5
U1  1.0000     NaN  0.3333  0.3700  0.90
U2     NaN  1.0000  0.6533  0.2133   NaN
U3  0.3333  0.6533  1.0000  0.5267  0.30
U4  0.3700  0.2133  0.5267  1.0000  0.34
U5  0.9000     NaN  0.3000  0.3400  1.00

==================================================
  KENDALL_TAU_B
==================================================

     U1   U2      U3      U4   U5
U1  1.0  NaN  1.0000     NaN  1.0
U2  NaN  1.0  1.0000     NaN  NaN
U3  1.0  1.0  1.0000  0.5774  1.0
U4  NaN  NaN  0.5774  1.0000  NaN
U5  1.0  NaN  1.0000     NaN  1.0

==================================================
  MANHATTAN
==================================================

        U1      U2      U3      U4    U5
U1  1.0000     NaN  1.0000  0.1667  0.25
U2     NaN  1.0000  0.3333  0.1429   NaN
U3  1.0000  0.3333  1.0000  0.1000  0.25
U4  0.1667  0.1429  0.1000  1.0000  0.20
U5  0.2500     NaN  0.2500  0.2000  1.00

==================================================
  MSD
==================================================

      U1    U2    U3    U4    U5
U1  1.00   NaN  1.00  0.74  0.90
U2   NaN  1.00  0.98  0.64   NaN
U3  1.00  0.98  1.00  0.79  0.90
U4  0.74  0.64  0.79  1.00  0.68
U5  0.90   NaN  0.90  0.68  1.00

==================================================
  PCC
==================================================

     U1   U2   U3   U4   U5
U1  1.0  NaN  1.0  0.0  1.0
U2  NaN  1.0  1.0  1.0  NaN
U3  1.0  1.0  1.0  0.5  1.0
U4  0.0  1.0  0.5  1.0  0.0
U5  1.0  NaN  1.0  0.0  1.0

==================================================
  SPCC
==================================================

        U1      U2      U3      U4      U5
U1  1.0000     NaN  0.7311  0.0000  0.7311
U2     NaN  1.0000  0.8808  0.7311     NaN
U3  0.7311  0.8808  1.0000  0.4404  0.7311
U4  0.0000  0.7311  0.4404  1.0000  0.0000
U5  0.7311     NaN  0.7311  0.0000  1.0000

==================================================
  SRC
==================================================

     U1   U2      U3      U4   U5
U1  1.0  NaN  1.0000     NaN  1.0
U2  NaN  1.0  1.0000     NaN  NaN
U3  1.0  1.0  1.0000  0.5774  1.0
U4  NaN  NaN  0.5774  1.0000  NaN
U5  1.0  NaN  1.0000     NaN  1.0